src/Entity/Car.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Car
{
    public static $brands = [
        0   => "Sceo",
        1   => "Oltcit",
        2   => "Ravon",
        3   => "Pontiac",
        4   => "Citroen",
        5   => "MG",
        6   => "JMC",
        7   => "Daihatsu",
        8   => "Geo",
        9   => "Pininfarina",
        10  => "Aro",
        11  => "Saab",
        12  => "Innocenti",
        13  => "Bio Auto",
        16  => "DS",
        17  => "Aixam",
        18  => "Ultima",
        19  => "Dagger",
        20  => "Fiat-Abarth",
        21  => "Rover",
        22  => "Volkswagen",
        23  => "Suzuki",
        24  => "MPM Motors",
        25  => "De Lorean",
        26  => "Rezvani",
        27  => "Artega",
        28  => "Wuling",
        29  => "Luxgen",
        31  => "Austin",
        32  => "Konecranes",
        33  => "Oldsmobile",
        34  => "KingWoo",
        35  => "Huabei",
        36  => "Detroit Electric",
        37  => "TVR",
        39  => "Gonow",
        40  => "Dadi",
        41  => "Zimmer",
        43  => "Ford",
        45  => "Daf",
        49  => "Buick",
        50  => "Hyundai",
        52  => "Triumph",
        53  => "Infiniti",
        54  => "Caterham",
        55  => "Bristol",
        57  => "Smart",
        58  => "Thunder Tiger",
        59  => "Seat",
        60  => "Lincoln",
        61  => "Austin-Healey",
        62  => "Kia",
        63  => "Iran Khodro",
        64  => "Cadillac",
        65  => "Volvo",
        67  => "Daewoo",
        68  => "Vepr",
        69  => "Xiaolong",
        70  => "Toyota",
        71  => "Fisker",
        74  => "Adler",
        77  => "Plymouth",
        78  => "Peugeot",
        81  => "Proton",
        84  => "LDV",
        88  => "Audi",
        89  => "Acura",
        90  => "Barkas (Баркас)",
        91  => "Shelby",
        93  => "SsangYong",
        97  => "Beijing",
        98  => "King Long",
        100 => "Morgan",
        102 => "Lexus",
        104 => "Daimler",
        106 => "Tofas",
        107 => "Chrysler",
        108 => "Miles",
        111 => "ItalCar",
        114 => "Haima",
        115 => "FAW",
        116 => "Maruti",
        120 => "Jaguar",
        121 => "McLaren",
        122 => "Zotye",
        123 => "Yugo",
        126 => "Humvee",
        128 => "Renault",
        130 => "Venturi",
        132 => "Pinzgauer",
        133 => "GMC",
        136 => "Subaru",
        138 => "Bentley",
        139 => "Fornasari",
        143 => "Alpine",
        144 => "Maybach",
        146 => "Pagani",
        148 => "Autobianchi",
        149 => "Mitsubishi",
        150 => "Abarth",
        151 => "Lotus",
        152 => "Packard",
        153 => "Norster",
        154 => "Maserati",
        155 => "Fiat",
        157 => "Lamborghini",
        159 => "Samand",
        162 => "Morris",
        164 => "Koenigsegg",
        167 => "Chevrolet",
        170 => "Wanfeng",
        171 => "Datsun",
        173 => "Scion",
        175 => "Saipa",
        178 => "FUQI",
        179 => "Nissan",
        180 => "Studebaker",
        181 => "Gac",
        186 => "Zastava",
        187 => "Alfa Romeo",
        194 => "Aston Martin",
        205 => "LTI",
        208 => "Hafei",
        211 => "SouEast",
        215 => "Peg-Perego",
        220 => "Dacia",
        224 => "Altamarea",
        225 => "Skoda",
        227 => "Kirkham",
        230 => "Sidetracker",
        235 => "Honda",
        236 => "Vauxhall",
        244 => "Shuanghuan",
        245 => "Ram",
        247 => "Humber",
        269 => "Dodge",
        276 => "Bertone",
        277 => "Talbot",
        283 => "Porsche",
        284 => "Soyat",
        286 => "MINI",
        296 => "Iveco",
        298 => "Praga Baby",
        306 => "Saleen",
        312 => "Hummer",
        313 => "Mahindra",
        319 => "Jinbei Minibusus",
        322 => "Ferrari",
        325 => "FSO",
        331 => "Great Wall",
        332 => "Mercury",
        343 => "Samson",
        358 => "Jeep",
        376 => "Blonell",
        392 => "Think Global",
        393 => "Mercedes-Benz",
        400 => "Land Rover",
        402 => "Geely",
        416 => "Opel",
        426 => "Renault Samsung Motors",
        428 => "Secma",
        437 => "BMW",
        441 => "Lancia",
        442 => "Bugatti",
        443 => "Rolls-Royce",
        467 => "Dr. Motor",
        485 => "Marshell"
    ];
    public static $energies = [0 => "diesel", 1 => "electric", 2 => "gas", 3 => "hybrid"];
    public static $categories = ["MPV" => "Monospace", "SUV" => "SUV", "convertible" => "Décapotable", "coupe" => "Coupé", "hatchback" => "Berline", "sedan" => "Berline Sport", "small" => "Citadine", "station wagon" => "Break"];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $year;

    /**
     * @ORM\Column(type="integer")
     */
    private $kilometrage;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $energie;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nbPorte;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $boite_de_vitesse;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $note;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $model;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isSelling;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPublished;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=510, nullable=true)
     */
    private $img;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getYear()
    {
        return $this->year;
    }

    public function setYear($year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getKilometrage(): ?int
    {
        return $this->kilometrage;
    }

    public function setKilometrage(int $kilometrage): self
    {
        $this->kilometrage = $kilometrage;

        return $this;
    }

    public function getEnergie(): ?string
    {
        return $this->energie;
    }

    public function setEnergie(string $energie): self
    {
        $this->energie = $energie;

        return $this;
    }

    public function getNbPorte(): ?int
    {
        return $this->nbPorte;
    }

    public function setNbPorte(?int $nbPorte): self
    {
        $this->nbPorte = $nbPorte;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getBoiteDeVitesse(): ?string
    {
        return $this->boite_de_vitesse;
    }

    public function setBoiteDeVitesse(?string $boite_de_vitesse): self
    {
        $this->boite_de_vitesse = $boite_de_vitesse;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getNote(): ?float
    {
        return $this->note;
    }

    public function setNote(?float $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getBrand()
    {
        return $this->brand;
    }

    /**
     * @param mixed $brand
     * @return Car
     */
    public function setBrand($brand)
    {
        $this->brand = $brand;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * @param mixed $model
     * @return Car
     */
    public function setModel($model)
    {
        $this->model = $model;
        return $this;
    }

    public function getIsSelling(): ?bool
    {
        return $this->isSelling;
    }

    public function setIsSelling(?bool $isSelling): self
    {
        $this->isSelling = $isSelling;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Form\CarType;
use App\Repository\CarRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FrontController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        return $this->render('front\index.html.twig');
    }

    /**
     * @Route("/search", name="search")
     * @param Request $request
     * @param CarRepository $carRepository
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function search(Request $request, CarRepository $carRepository, PaginatorInterface $paginator)
    {
        $search = $request->query->get('search');

        if ($search != '') {
            $query = $carRepository->findByTerms($search);
        } else {
            $criteria['brand'] = $request->query->get('brandSearch');
            $criteria['energie'] = $request->query->get('energieSearch');
            $criteria['category'] = $request->query->get('categorySearch');
            $criteria['year'] = $request->query->get('yearSearch');
            $criteria['nbPorte'] = $request->query->get('nbPorteSearch');
            $criteria['boite_de_vitesse'] = $request->query->get('boite_de_vitesseSearch');

            $query = $carRepository->findByCriteria($criteria);
        }

        $cars = $paginator->paginate(
            $query, /* query NOT result */
            $request->query->getInt('page', 1), /*page number*/
            18 /*limit per page*/
        );

        $allCars = $carRepository->findAll();
        $years = [];
        foreach ($allCars as $allCar) {
            $years[] = $allCar->getYear();
        }
        $energies = Car::$energies;
        $brands = Car::$brands;
        $categories = Car::$categories;
        $years = array_unique($years);

        sort($brands);
        sort($years);

        return $this->render('front\search.html.twig', [
            'search'     => $search,
            'cars'       => $cars,
            'brands'     => $brands,
            'energies'   => $energies,
            'categories' => $categories,
            'years'      => $years
        ]);
    }

    /**
     * @Route("/addCar", name="addCar")
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function addCar(Request $request)
    {
        $car = new Car();

        $form = $this->createForm(CarType::class, $car);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $car = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($car);
            $entityManager->flush();

            return $this->redirectToRoute('search');
        }

        return $this->render('front/newCar.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/car/{id}", name="showCar")
     * @param $id
     * @param CarRepository $carRepository
     * @return Response
     */
    public function showCar($id, CarRepository $carRepository)
    {
        $car = $carRepository->find($id);
        $categories = Car::$categories;

        return $this->render('front/showCar.html.twig', ['car' => $car, 'categories' => $categories]);
    }

    /**
     * @Route("/sellCar/{id}", name="sellCar")
     * @param $id
     * @param CarRepository $carRepository
     * @return RedirectResponse
     */
    public function sellCar($id, CarRepository $carRepository) {
        $em = $this->getDoctrine()->getManager();

        $car = $carRepository->find($id);
        $car->setIsSelling(true);

        $em->persist($car);
        $em->flush();

        return $this->redirectToRoute('showCar', ['id' => $id]);
    }
}

templates/front/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <!--Main Navigation-->
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container">
                <a class="navbar-brand" href="#"><strong>Auto Vente</strong></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('addCar') }}">Vendre mon véhicule</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="view intro-2">
            <div class="full-bg-img">
                <div class="mask rgba-indigo-slight flex-center">
                    <div class="container">
                        <div class="text-center wow fadeInUp">
                            <form action="{{ path('search') }}" class="card col-md-4 py-4">
                                <h3 class="font-weight-bolder">Rechercher une marque, un modèle...</h3>
                                <div class="form-group">
                                    <input type="search" class="form-control" name="search" id="model" placeholder="ex: Clio">
                                </div>
                                <input type="submit" class="btn btn-danger" value="Rechercher">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </header>
    <!--Main Navigation-->

    <!--Main Layout-->
    <main class="text-center py-5 mt-3">

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p align="justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                        voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                </div>
            </div>
        </div>

    </main>
    <!--Main Layout-->
{% endblock %}

templates/front/newCar.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% include 'front/includes/navbar.html.twig' %}
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6">
                <h3>Vendre mon véhicule</h3>
                <small class="text-danger">(Votre annonce sera validée par notre équipe avant sa publication)</small>
                {{ form(form) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $('select').select2();
    </script>
{% endblock %}

templates/front/showCar.html.twig
{% extends 'base.html.twig' %}

{% block style %}
    <style>
        .info {
            font-weight: 600;
        }
    </style>
{% endblock %}

{% block body %}
    {% include 'front/includes/navbar.html.twig' %}
    <div class="container-fluid p-5">
        <div class="row">
            <div class="col-md-4">
                <h3>{{ car.brand }} {{ car.model }}</h3>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th class="info">Année</th>
                        <td>{{ car.year }}</td>
                    </tr>
                    <tr>
                        <th class="info">Marque</th>
                        <td>{{ car.brand }}</td>
                    </tr>
                    <tr>
                        <th class="info">Modèle</th>
                        <td>{{ car.model }}</td>
                    </tr>
                    <tr>
                        <th class="info">Kilometrage</th>
                        <td>{{ car.kilometrage }} km</td>
                    </tr>

                    <tr>
                        <th class="info">Carburant</th>
                        <td>{{ car.energie|capitalize }}</td>
                    </tr>
                    <tr>
                        <th class="info">Ville</th>
                        <td>{{ car.city }}</td>
                    </tr>
                    <tr>
                        <th class="info">Nombre de porte</th>
                        <td>{{ car.nbPorte }}</td>
                    </tr>
                    <tr>
                        <th valign="top" class="info">Catégorie</th>
                        <td>{{ categories[car.category] }}</td>
                    </tr>
                    <tr>
                        <th class="info">Boite de vitesse</th>
                        <td>{{car.boiteDeVitesse}}</td>
                    </tr>
                    <tr>
                        <th class="info">Publié le </th>
                        <td>{{car.createdAt|date('d/m/Y')}}</td>
                    </tr>
                    </thead>

                </table>
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d10558.73061674311!2d1.60369505!3d48.577626599999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1581949741023!5m2!1sfr!2sfr" width="100%" height="350" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
            </div>
            <div class="col-md-8">
                <div class="card">

                    <!--Card image-->
                    <img class="card-img-top" src="{{car.img}}" alt="Card image cap">

                    <!--Card content-->
                    <div class="card-body">

                        <!-- Container -->
                        <div class="d-block d-flex justify-content-center">

                            <!-- Column -->
                            <div class="p-3 col-md-6">

                                <h3 class="pb-3 font-weight-bold d-flex justify-content-between"><span>{{ car.brand }} {{ car.model }}</span><span><i class="fas fa-star text-warning"></i>{{ car.note|number_format(1,',', ' ') }}</span></h3>
                                <p align="justify">{{ car.description }}</p>

                            </div>
                            <!-- Column -->

                        </div>
                        <!-- Container -->
                        {% if car.isSelling != true %}
                        <div class="text-center">
                            <a href="{{ path('sellCar', {'id': car.id}) }}" class="btn btn-danger">Acheter {{ car.prix }} €</a>
                        </div>
                        {% else %}
                            <div class="text-center">
                                <button class="btn btn-danger disabled">Vendu {{ car.prix }} €</button>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
{{ parent() }}
{% endblock %}